name: "Generate gtest failure message"
description: "Generate gtest failure message for Github workflow annotations"

inputs:
  path:
    description: "Paths to pass containing gtest XML files"
    required: false
    default: "/work/generated/test_reports/"
  metal-repo-path:
    description: "Paths to metal repository"
    required: false
    default: "/work"

runs:
  using: "composite"
  steps:
    - name: Generate gtest failure messages
      id: generate-gtest-message
      working-directory: ${{ inputs.metal-repo-path || '/work' }}
      shell: bash
      run: |
        set +e
        python3 .github/scripts/data_analysis/print_gtest_annotations.py ${{ inputs.path }}
