set(CPACK_GENERATOR DEB)
set(CPACK_PACKAGE_CONTACT "support@tenstorrent.com")
set(CMAKE_PROJECT_HOMEPAGE_URL "https://tenstorrent.com")
#set(CPACK_DEBIAN_PACKAGE_MAINTAINER "support@tenstorrent.com")
string(TOLOWER ${PROJECT_NAME} CPACK_PACKAGE_NAME)

set(CPACK_COMPONENT_sdk_DESCRIPTION "For building apps")
set(CPACK_DEBIAN_sdk_PACKAGE_SECTION "libdevel")
set(CPACK_COMPONENT_runtime_DESCRIPTION "For using apps")
set(CPACK_DEBIAN_runtime_PACKAGE_SECTION "libs")

set(CPACK_COMPONENT_examples_DESCRIPTION "Some examples")
set(CPACK_DEBIAN_doc_PACKAGE_SECTION "doc")
set(CPACK_DEBIAN_sdk_PACKAGE_SECTION "libdevel")

set(CPACK_DEB_COMPONENT_INSTALL TRUE)
# set(CPACK_DEBIAN_PACKAGE_VERSION "0.1.2.3~rc3")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)
# CPACK_DEBIAN_PACKAGE_SOURCE
# CPACK_DEBIAN_<COMPONENT>_PACKAGE_MULTIARCH

#set(CPACK_DEBIAN_PACKAGE_NAME ${CPACK_PACKAGE_NAME})$
#set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
#set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS ...)
# TODO set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)
# CPACK_DEBIAN_<COMPONENT>_PACKAGE_CONFLICTS
# CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS

include(CPack)
