name: "[internal] Slow Dispatch unit tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 35
      os:
        required: false
        type: string
        default: "ubuntu-20.04"
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - wormhole_b0
          - blackhole
      runner-label:
        required: true
        type: choice
        options:
          - E150
          - N150
          - N300
          - BH
      timeout:
        required: false
        type: number
        default: 35
      os:
        required: false
        type: string
        default: "ubuntu-20.04"

jobs:
  cpp-unit-tests-slow-dispatch:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group: [
          {name: All C++, cmd: ./tests/scripts/run_cpp_unit_tests.sh},
          {name: user kernel path, cmd: "rm -rf /tmp/kernels && TT_METAL_KERNEL_PATH=/tmp/kernels ./build/test/tt_metal/unit_tests_api_${{ inputs.arch }} --gtest_filter=CompileProgramWithKernelPathEnvVarFixture.*"},
          {name: api, cmd: "./build/test/tt_metal/unit_tests_api_${{ inputs.arch }}"},
          {name: debug_tools, cmd: "./build/test/tt_metal/unit_tests_debug_tools_${{ inputs.arch }}"},
          {name: device, cmd: "./build/test/tt_metal/unit_tests_device"},
          {name: dispatch, cmd: "./build/test/tt_metal/unit_tests_dispatch"},
          {name: eth, cmd: "./build/test/tt_metal/unit_tests_eth_${{ inputs.arch }}"},
          {name: llk, cmd: "./build/test/tt_metal/unit_tests_llk"},
          {name: stl, cmd: "./build/test/tt_metal/unit_tests_stl"},
          {name: distributed, cmd: "./build/test/tt_metal/distributed/distributed_unit_tests_${{ inputs.arch }} --gtest_filter=MeshDeviceSuite.*"},
          {name: FD2, cmd: ./tests/scripts/run_cpp_fd2_tests.sh},
        ]
    name: ${{ inputs.arch }} ${{ inputs.runner-label }} ${{ matrix.test-group.name }}
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/prepare-metal-run
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ inputs.timeout }}
        uses: ./.github/actions/docker-run
        with:
          docker_os_arch: tt-metalium/${{ inputs.os }}-dev-amd64
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          docker_opts: |
            -e ARCH_NAME=${{ inputs.arch}}
            -e TT_METAL_HOME=${{ github.workspace }}
            -e TT_METAL_SLOW_DISPATCH_MODE=1
            -e LD_LIBRARY_PATH=${{ github.workspace }}/build/lib
            -e GTEST_OUTPUT=xml:generated/test_reports/
          run_args: |
            pip install --force-reinstall pip==21.2.4
            pip install -r tt_metal/python_env/requirements-dev.txt
            pip install -e .
            mkdir -p generated/test_reports
            ${{ matrix.test-group.cmd }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U06CXU895AP # Michael Chiou
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
      - name: Generate system logs on failure
        uses: ./.github/actions/generate-system-logs
        if: ${{ failure() }}
      - name: Generate gtest annotations on failure
        uses: ./.github/actions/generate-gtest-failure-message
        if: ${{ failure() }}
        with:
          path: |
            generated/test_reports/
