name: Nightly slow dispatch tests

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 1,6 * * *"

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  frequent-slow-dispatch:
    needs: build-artifact
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        arch: [wormhole_b0]
        frequent-type: [api]
    env:
      ARCH_NAME: ${{ matrix.arch }}
      LOGURU_LEVEL: INFO
      TT_METAL_SLOW_DISPATCH_MODE: 1
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ["model-runner-${{ matrix.arch }}", "in-service"]
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/ensure-active-weka-mount
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        timeout-minutes: 10
        with:
          name: TTMetal_build_any
      - name: Extract files
        run: tar -xvf ttm_any.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run frequent reg tests scripts
        timeout-minutes: 210
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.arch }} --pipeline-type frequent_${{ matrix.frequent-type }} --dispatch-mode slow
