name: "[internal] models tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 45
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - wormhole_b0
          - blackhole
      runner-label:
        required: true
        type: choice
        options:
          - N150
          - N300
          - BH
      timeout:
        required: false
        type: number
        default: 45

jobs:
  models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        test-group: [
          {name: model},
        ]
    name: ${{ matrix.test-group.name }} ${{ inputs.arch }} ${{ inputs.runner-label }}
    env:
      LOGURU_LEVEL: INFO
    runs-on:
      - ${{ inputs.runner-label }}
      - in-service
      - cloud-virtual-machine
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/retry-command
        # For BH we use yyzo machines and they don't have MLPerf mounted
        if: ${{ inputs.arch != 'blackhole' }}
        with:
          timeout-seconds: 100
          max-retries: 10
          backoff-seconds: 60
          command: ./.github/scripts/cloud_utils/mount_weka.sh
      - uses: actions/download-artifact@v4
        timeout-minutes: 10
        with:
          name: eager-dist-${{ matrix.os }}-any
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ inputs.timeout }}
        uses: ./.github/actions/docker-run
        with:
          install_wheel: true
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          docker_opts: |
            -e ARCH_NAME=${{ inputs.arch }}
            -e GITHUB_ACTIONS=true
          run_args: |
            source tests/scripts/run_python_model_tests.sh && run_python_model_tests_${{ inputs.arch }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U06CXU895AP # Michael Chiou
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"

  models-tests-slow-runtime-mode:
    # BH runs only FD tests to avoid using too many CI resources
    if: ${{ inputs.arch != 'blackhole' }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        test-group: [
          {name: model},
        ]
    name: models slow dispatch
    env:
      LOGURU_LEVEL: INFO
    runs-on:
      - ${{ inputs.runner-label }}
      - in-service
      - cloud-virtual-machine
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/retry-command
        with:
          timeout-seconds: 100
          max-retries: 10
          backoff-seconds: 60
          command: ./.github/scripts/cloud_utils/mount_weka.sh
      - uses: actions/download-artifact@v4
        timeout-minutes: 10
        with:
          name: eager-dist-${{ matrix.os }}-any
      - name: ${{ matrix.test-group.name }} slow runtime mode tests
        timeout-minutes: ${{ inputs.timeout }}
        uses: ./.github/actions/docker-run
        with:
          install_wheel: true
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          docker_opts: |
            -e ARCH_NAME=${{ inputs.arch }}
            -e SLOW_RUNTIME_MODE=true
          run_args: |
            source tests/scripts/run_python_model_tests.sh && run_python_model_tests_slow_runtime_mode_${{ inputs.arch }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U06CXU895AP # Michael Chiou
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
