name: "Sliding window test suite"

on:
  workflow_dispatch:
    inputs:
      build-with-tracy:
        required: false
        type: boolean
        default: true
      post-commit:
        required: false
        type: boolean
        default: true
      bh-post-commit:
        required: false
        type: boolean
        default: true
      single-card-perf-models:
        required: false
        type: boolean
        default: true
      single-card-perf-device-models:
        description: "perf-device (requires tracy build)"
        required: false
        type: boolean
        default: true
      single-card-l2-nightly:
        required: false
        type: boolean
        default: true
      single-card-frequent-models-nightly:
        required: false
        type: boolean
        default: true

run-name: ${{ inputs.description }}
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      build-type: ${{ inputs.build-type }}
      tracy: ${{ inputs.build-with-tracy }}
      build-wheel: true
      version: "22.04"
    secrets: inherit
  single-card-perf-models-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/perf-models-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
    if: ${{ inputs.single-card-perf-models }}
  single-card-perf-device-models-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/perf-device-models-impl.yaml
    if: ${{ inputs.single-card-perf-device-models }}
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
  single-card-frequent-models-and-ttnn-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/fast-dispatch-full-regressions-and-models-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
    if: ${{ inputs.single-card-nightly }}
  l2-wormhole-tests:
    needs: build-artifact
    strategy:
      fail-fast: false
      matrix:
        target: ['wormhole_b0', 'blackhole']
        test-group:
          - name: ttnn nightly conv tests
            cmd: pytest tests/ttnn/nightly/unit_tests/operations/conv -xv -m "not disable_fast_runtime_mode"
          - name: ttnn nightly pool tests
            cmd: pytest tests/ttnn/nightly/unit_tests/operations/pool -xv -m "not disable_fast_runtime_mode"
    container:
      image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      env:
        PYTHONPATH: /work
        LD_LIBRARY_PATH: /work/build/lib
        ARCH_NAME: ${{ matrix.version }}
        LOGURU_LEVEL: INFO
      volumes:
        - ${{ github.workspace }}/docker-job:/work # Subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
      options: "--device /dev/tenstorrent"
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    name: ${{ matrix.test-group.name }}
    runs-on:
      - ${{ matrix.target == 'wormhole_b0' && 'N150' || 'BH' }}
      - "in-service"
    steps:
      - name: ⬇️  Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@main
        timeout-minutes: 10
        with:
          build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
          wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ (github.event_name == 'schedule' && 120) || fromJSON(inputs.timeout) }}
        run: ${{ matrix.test-group.cmd }}
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          prefix: "test_reports_"
      - uses: tenstorrent/tt-metal/.github/actions/cleanup@main
        if: always()
