name: "Galaxy Quick"

on:
  workflow_dispatch:
    inputs:
      topology-4u:
        required: false
        type: boolean
        default: true
      topology-6u:
        required: false
        type: boolean
        default: true
  push:
    branches: ["main"]

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
      version: 22.04

  tg-quick-test:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-quick.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      topology-4u: ${{ inputs.topology-4u || true }}
      topology-6u: ${{ inputs.topology-6u || false }}
