name: Build test and publish upstream tests

on:
  push:
    branches:
      - rkim/21067-upstream-tests
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      version: 22.04
      build-wheel: true
  build-wh-6u-image:
    needs: build-artifact
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.set-wh-6u-image-name.outputs.wh-6u-image-name }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set image name
        id: set-wh-6u-image-name
        run: echo "wh-6u-image-name=ghcr.io/tenstorrent/tt-metal/upstream-tests-wh-6u:${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - name: Download artifacts from metal
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          # 22.04 artifact... we'll probably need to key on that in the original action in metal
          name: TTMetal_build_any
      - run: mkdir -p _tt-metal
      - run: tar -xvf ttm_any.tar -C _tt-metal/
      - run: ls -hal _tt-metal
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfile/upstream_test_images/Dockerfile.wh-6u
          platforms: linux/amd64
          pull: true
          push: true
          # https://github.com/docker/build-push-action/issues/557#issuecomment-1030412477
          build-args: |
            TT_METAL_DEV_VERSION=latest
            TT_METAL_COMMIT_SHA=${{ github.sha }}
          # Use run_number as it should be unique for every run, can trace to a commit, and is a
          # static counter managed by GitHub
          tags: ${{ steps.set-wh-6u-image-name.outputs.wh-6u-image-name }}
          context: ${{ github.workspace }}
  test-wh-6u-image:
    needs: build-wh-6u-image
    runs-on:
      - arch-wormhole_b0
      - topology-6u
      - in-service
      - pipeline-functional
    steps:
      - name: Pull image
        timeout-minutes: 10
        run: docker pull ${{ needs.build-wh-6u-image.outputs.image-name }}
      - name: Run image
        timeout-minutes: 10
        run: docker run -v /dev/hugepages-1G:/dev/hugepages-1G --device /dev/tenstorrent ${{ needs.build-wh-6u-image.outputs.image-name }}
