name: Build test and publish upstream tests

on:
  push:
    branches:
      - rkim/21067-upstream-tests
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      version: 22.04
      build-wheel: true
  build-6u-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from metal
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          # 22.04 artifact... we'll probably need to key on that in the original action in metal
          name: TTMetal_build_any
      - run: mkdir -p _tt-metal
      - run: tar -xvf ttm_any.tar -C _tt-metal/
      - run: ls -hal _tt-metal
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfile/upstream_test_images/Dockerfile.6u
          platforms: linux/amd64
          pull: true
          push: true
          # https://github.com/docker/build-push-action/issues/557#issuecomment-1030412477
          build-args: |
            TT_METAL_DEV_VERSION=latest
            TT_METAL_COMMIT_SHA=${{ github.sha }}
          # Use run_number as it should be unique for every run, can trace to a commit, and is a
          # static counter managed by GitHub
          tags: ghcr.io/tenstorrent/tt-metal/upstream-tests-6u:${{ github.run_number }}
          context: ${{ github.workspace }}
